import db from './db';

export function createUser(email, password) {
  const result = db
    .prepare('INSERT INTO users (email, password) VALUES (?, ?)')
    .run(email, password);
  // Return the ID of the newly created user record.
  // This is the unique identifier automatically generated by the database,
  // which can be used to reference this user in future operations.
  return result.lastInsertRowid;
}
